# Generated by Django 4.1.2 on 2023-12-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberId', models.CharField(max_length=10, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('zoneNumber', models.CharField(max_length=100)),
                ('society', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('givenName', models.CharField(max_length=100)),
                ('middleName', models.CharField(blank=True, max_length=100, null=True)),
                ('dateOfBirth', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('hometown', models.CharField(max_length=100)),
                ('hometownRegion', models.CharField(max_length=100)),
                ('idNumber', models.CharField(max_length=100)),
                ('levelOfEducation', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('altContact', models.CharField(blank=True, max_length=100, null=True)),
                ('maritalStatus', models.CharField(max_length=100)),
                ('familySize', models.CharField(blank=True, max_length=100, null=True)),
                ('nextOfKingFullname', models.CharField(max_length=100)),
                ('relationshipWithNOK', models.CharField(max_length=100)),
                ('nokContact', models.CharField(blank=True, max_length=100, null=True)),
                ('farmOwner', models.CharField(max_length=100)),
                ('farmSize', models.CharField(blank=True, max_length=100, null=True)),
                ('numberOfLabourers', models.CharField(blank=True, max_length=100, null=True)),
                ('farmLocation', models.CharField(max_length=100)),
                ('averageCropYield', models.CharField(max_length=100)),
                ('supportingBusiness', models.CharField(blank=True, max_length=100, null=True)),
                ('buyerOfProduce', models.CharField(blank=True, max_length=100, null=True)),
                ('reasonForChoosingBuyer', models.CharField(blank=True, max_length=100, null=True)),
                ('fundInterest', models.CharField(blank=True, max_length=100, null=True)),
                ('interestSpecify', models.CharField(blank=True, max_length=100, null=True)),
                ('bankTransactingWith', models.CharField(max_length=100)),
                ('numberOfYears', models.CharField(max_length=100)),
                ('partOfAssociation', models.CharField(max_length=100)),
                ('associationSpecify', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
