# Generated by Django 4.1.2 on 2024-01-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, default='image.png', null=True, upload_to='members_id'),
        ),
    ]
