# Generated by Django 4.1.2 on 2024-02-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_member_address_alter_member_averagecropyield_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='oldMemberId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
